#compdef bob
# Generated by bob completion (protocol 1). Do not edit: run `bob completion install`.
# Each <TAB> asks the `bob` on your PATH, so completion always matches the installed binary.

_bob() {
  local -a lines fields groups
  local -A arrays
  local line value help group suffix array header ret=1

  lines=(${(f)"$(command bob __complete zsh --protocol 1 --suffix "$SUFFIX" -- \
    "${(@Q)words[1,CURRENT-1]}" "$PREFIX" 2>/dev/null)"})
  (( $#lines )) || return 1

  # Bob-scoped presentation defaults, applied only where you have set no style.
  if ! zstyle -m ":completion:${curcontext}:descriptions" format '*'; then
    header='%B%F{green}── %d ──%f%b'
    (( ${+NO_COLOR} )) && header='── %d ──'
    zstyle ':completion:*:*:bob:*:descriptions' format "$header"
  fi
  zstyle -m ":completion:${curcontext}:" group-name '*' ||
    zstyle ':completion:*:*:bob:*' group-name ''

  for line in $lines; do
    case $line in
      ('!prefix '<->) compset -P ${line#!prefix }; continue ;;
      ('!dirs')       _files -/ && ret=0; continue ;;
      ('!files')      _files && ret=0; continue ;;
      ('!files '*)    _files -g "${line#!files }" && ret=0; continue ;;
      ('!files-in '*) fields=("${(@ps:\t:)${line#!files-in }}")
                      _files -W "$fields[1]" -g "$fields[2]" && ret=0; continue ;;
      ('!message '*)  _message -r "${line#!message }"; continue ;;
      ('!'*)          continue ;;  # a directive from a newer bob: ignore it
    esac
    fields=("${(@ps:\t:)line}")
    value=${fields[1]//:/\\:} help=$fields[2] group=${fields[3]:-values} suffix=${fields[4]:-space}
    array=$arrays[$group/$suffix]
    if [[ -z $array ]]; then
      array=_bob_group_$#groups
      arrays[$group/$suffix]=$array
      groups+=("$group/$suffix")
      local -a $array
    fi
    set -A $array "${(@P)array}" "$value${help:+:$help}"
  done

  for group in $groups; do
    array=$arrays[$group]
    suffix=${group##*/} group=${group%/*}
    if [[ $suffix == nospace ]]; then
      _describe -V -t "${group// /-}" "$group" $array -S '' && ret=0
    else
      _describe -V -t "${group// /-}" "$group" $array && ret=0
    fi
  done
  return ret
}

if [[ $zsh_eval_context[-1] == loadautofunc ]]; then
  _bob "$@"
else
  compdef _bob bob
fi
