# bob completion for bash — installed by `bob completion install`.
# Generated by bob completion (protocol 1). Do not edit: run `bob completion install`.
# Each <TAB> asks the `bob` on your PATH, so completion always matches the installed binary.

_bob() {
  local line_before="${COMP_LINE:0:COMP_POINT}" line_after="${COMP_LINE:COMP_POINT}"
  local -a words=() out=()
  local prefix="" suffix="" cur_word="" c
  local in_single=0 in_double=0 escaped=0 ends_space=0 i
  for ((i = 0; i < ${#line_before}; i++)); do
    c="${line_before:i:1}"
    if ((escaped)); then cur_word+="$c"; escaped=0; ends_space=0; continue; fi
    if ((in_single)); then if [[ "$c" == "'" ]]; then in_single=0; else cur_word+="$c"; fi; continue; fi
    if ((in_double)); then
      if [[ "$c" == '"' ]]; then in_double=0; elif [[ "$c" == "\\" ]]; then escaped=1; else cur_word+="$c"; fi
      continue
    fi
    case "$c" in
      \\) escaped=1 ;;
      "'") in_single=1; ends_space=0 ;;
      '"') in_double=1; ends_space=0 ;;
      ' '|$'\t'|$'\n')
        [[ -n "$cur_word" ]] && words+=("$cur_word")
        cur_word=""; ends_space=1 ;;
      *) cur_word+="$c"; ends_space=0 ;;
    esac
  done
  if ((ends_space)); then prefix=""; [[ -n "$cur_word" ]] && words+=("$cur_word"); words+=("")
  else prefix="$cur_word"; words+=("$cur_word"); fi
  if [[ -n "$line_after" && "$line_after" != [[:space:]]* ]]; then
    suffix="${line_after%%[[:space:]]*}"; suffix="${suffix//\'/}"; suffix="${suffix//\"/}"
  fi
  if [[ -n "$suffix" ]]; then
    mapfile -t out < <(command bob __complete bash --protocol 1 --suffix "$suffix" -- "${words[@]}" 2>/dev/null)
  else
    mapfile -t out < <(command bob __complete bash --protocol 1 -- "${words[@]}" 2>/dev/null)
  fi
  (( ${#out[@]} )) || { COMPREPLY=(); return 0; }
  local keep=0 line val _desc _group sp
  local has_dirs=0 has_files=0 files_glob="" filesin_root="" filesin_glob=""
  local -a vals=() is_nospace=()
  for line in "${out[@]}"; do
    case "$line" in
      '!prefix '*) keep="${line#!prefix }" ;;
      '!dirs') has_dirs=1 ;;
      '!files') has_files=1 ;;
      '!files '*) has_files=1; files_glob="${line#!files }" ;;
      '!files-in '*) has_files=2; local rest="${line#!files-in }"; filesin_root="${rest%%$'\t'*}"; filesin_glob="${rest#*$'\t'}" ;;
      '!message '*) COMPREPLY=(); return 0 ;;
      '!'*) continue ;;
      *) IFS=$'\t' read -r val _desc _group sp <<<"$line"
        [[ -n "$val" ]] || continue
        vals+=("$val"); [[ "$sp" == "nospace" ]] && is_nospace+=(1) || is_nospace+=(0) ;;
    esac
  done
  local cur_broken="${COMP_WORDS[COMP_CWORD]:-$prefix}"
  if ((has_dirs)); then
    COMPREPLY=($(compgen -d -- "$cur_broken")); compopt -o filenames 2>/dev/null; return 0
  fi
  if ((has_files == 1)); then
    local -a all=() kept=()
    mapfile -t all < <(compgen -f -- "$cur_broken")
    for val in "${all[@]}"; do [[ -z "$files_glob" || "$val" == $files_glob ]] && kept+=("$val"); done
    COMPREPLY=("${kept[@]}"); compopt -o filenames 2>/dev/null; return 0
  fi
  # The cursor-word text readline will replace: everything up to and
  # including the last wordbreak character, whatever it is (`=`, `:`,
  # …). An open quote replaces the whole quoted text instead, so there
  # is no stripping there.
  local kept="${prefix:0:keep}"
  local rest="${prefix:keep}"
  local strip=""
  if (( ! in_single && ! in_double )); then
    local after_last="${prefix##*["$COMP_WORDBREAKS"]}"
    if [[ "$after_last" != "$prefix" ]]; then
      strip="${prefix%"$after_last"}"
    fi
  fi
  if ((has_files == 2)); then
    local -a kept=()
    local name
    while IFS= read -r -d '' val; do
      name="${val#"$filesin_root/"}"
      [[ "$name" == "$rest"* ]] || continue
      kept+=("${name#"$strip"}")
    done < <(find "$filesin_root" -type f -name "$filesin_glob" -print0 2>/dev/null)
    COMPREPLY=("${kept[@]}"); compopt -o filenames 2>/dev/null; return 0
  fi
  local -a filtered=() filtered_nos=()
  local reply quoted
  for i in "${!vals[@]}"; do
    [[ "${vals[i]}" == "$rest"* ]] || continue
    reply="$kept${vals[i]}"
    if (( in_single || in_double )); then
      # Open quote: readline replaces the whole quoted text, so reply
      # with the kept text plus the value unescaped; readline adds the
      # closing quote itself.
      filtered+=("$reply")
    else
      # Unquoted: readline replaces only its own current word, and each
      # value must stay one argument.
      reply="${reply#"$strip"}"
      printf -v quoted %q "$reply"
      filtered+=("$quoted")
    fi
    filtered_nos+=("${is_nospace[i]}")
  done
  COMPREPLY=("${filtered[@]}")
  if ((${#filtered[@]})); then
    local all_nos=1
    for i in "${!filtered_nos[@]}"; do ((filtered_nos[i])) || { all_nos=0; break; }; done
    ((all_nos)) && compopt -o nospace 2>/dev/null
  fi
  return 0
}
complete -F _bob bob
