//! Shell adapters installed by `bob completion install`.
//!
//! The adapters are small, stable, protocol-versioned renderers: every
//! TAB runs `bob __complete` against the binary on `PATH` and renders
//! what it returns, so completion always matches the installed binary.
//! Adapters never parse bob syntax themselves. (Wired to the shell by
//! the `bob completion` command in the lifecycle phase.)

/// The embedded `_bob` zsh adapter.
pub(crate) fn zsh_adapter() -> &'static str {
    include_str!("adapters/_bob.zsh")
}

#[cfg(test)]
mod tests {
    use super::super::protocol::PROTOCOL;
    use super::zsh_adapter;

    #[test]
    fn zsh_stamp_matches_protocol() {
        let mut lines = zsh_adapter().lines();
        assert_eq!(lines.next(), Some("#compdef bob"));
        let stamp = lines.next().expect("adapter has a stamp line");
        assert_eq!(
            stamp,
            format!(
                "# Generated by bob completion (protocol {PROTOCOL}). \
                 Do not edit: run `bob completion install`."
            )
        );
    }
}
