//! `bob completion` runtime: install, status, uninstall, and adapter print.
//!
//! Install writes the adapter atomically, refuses files bob did not write
//! without `--force`, verifies registration with a real-shell probe unless
//! told not to, and records everything in the manifest. Status never writes.
//! Exit codes: 0 for success or an explicit no-op, 1 for a failed install
//! or uninstall (verification problems are notes on install but fail
//! `status -v`, whose job is liveness), 2 for usage errors.

use std::ffi::OsString;
use std::path::{Path, PathBuf};

use super::cli::{build_cli, Shell};
use super::manifest::{self, Manifest, VerificationRecord};
use super::protocol::PROTOCOL;
use super::report::{self, Level, Report, ShellRow, State, TargetReason};
use super::verify::{self, Registration};
use crate::native::env;
use crate::native::style::Styler;

pub(crate) fn run(args: Vec<OsString>) -> i32 {
    let mut command = build_cli();
    let matches = match command.try_get_matches_from_mut(
        std::iter::once(OsString::from("bob completion")).chain(args),
    ) {
        Ok(matches) => matches,
        Err(error) => {
            let code = error.exit_code();
            if let Err(print_error) = error.print() {
                eprintln!(
                    "bob completion: failed to print command-line error: {print_error}"
                );
            }
            return code;
        }
    };
    match matches.subcommand() {
        Some(("install", sub)) => run_install(sub),
        Some(("status", sub)) => run_status(
            sub.get_flag("json"),
            sub.get_flag("verify"),
            selected_or_all(sub, StatusDefault::All),
        ),
        Some(("uninstall", sub)) => run_uninstall(sub),
        Some(("bash", sub)) => {
            run_print(Shell::Bash, sub.get_one::<String>("output"))
        }
        Some(("zsh", sub)) => {
            run_print(Shell::Zsh, sub.get_one::<String>("output"))
        }
        Some((name, _)) => {
            eprintln!("bob completion: unknown subcommand: {name}");
            2
        }
        None => run_status(
            matches.get_flag("json"),
            matches.get_flag("verify"),
            Shell::all().to_vec(),
        ),
    }
}

fn selected_or_all(
    matches: &clap::ArgMatches,
    default: StatusDefault,
) -> Vec<Shell> {
    let explicit: Vec<Shell> = matches
        .try_get_many::<String>("shell")
        .ok()
        .flatten()
        .map(|values| values.filter_map(|raw| Shell::parse(raw)).collect())
        .unwrap_or_default();
    if !explicit.is_empty() {
        let mut seen = Vec::new();
        for shell in explicit {
            if !seen.contains(&shell) {
                seen.push(shell);
            }
        }
        return seen;
    }
    match default {
        StatusDefault::All => Shell::all().to_vec(),
        StatusDefault::Owned(manifest) => manifest.owned_shells(),
    }
}

enum StatusDefault<'a> {
    All,
    Owned(&'a Manifest),
}

// --- adapter bytes and stamp ---------------------------------------------

fn adapter_text(shell: Shell) -> &'static str {
    match shell {
        Shell::Bash => super::adapters::bash_adapter(),
        Shell::Zsh => super::adapters::zsh_adapter(),
    }
}

fn expected_stamp() -> String {
    format!(
        "# Generated by bob completion (protocol {PROTOCOL}). \
         Do not edit: run `bob completion install`."
    )
}

fn has_stamp(shell: Shell, bytes: &[u8]) -> bool {
    let text = String::from_utf8_lossy(bytes);
    let stamp = expected_stamp();
    let stamped = text.lines().take(5).any(|line| line == stamp);
    if !stamped {
        return false;
    }
    match shell {
        Shell::Zsh => text.lines().next() == Some("#compdef bob"),
        Shell::Bash => text.contains("complete -F _bob bob"),
    }
}

// --- target discovery -----------------------------------------------------

pub(crate) struct Target {
    path: PathBuf,
    reason: TargetReason,
}

fn absolutize(path: &Path) -> Result<PathBuf, String> {
    if path.is_absolute() {
        return Ok(path.to_path_buf());
    }
    let cwd = std::env::current_dir().map_err(|error| {
        format!("cannot resolve working directory: {error}")
    })?;
    Ok(cwd.join(path))
}

/// Resolve where the `shell` adapter should live.
///
/// For zsh the first match wins: `--target`, the manifest location, the
/// first under-`$HOME` user-owned writable fpath entry outside
/// plugin-manager, cache, and oh-my-zsh trees, oh-my-zsh completions,
/// then `~/.zfunc`. For bash it is `--target`, the manifest location,
/// then `${BASH_COMPLETION_USER_DIR:-${XDG_DATA_HOME:-~/.local/share}/bash-completion}/completions/bob`.
fn resolve_target(
    shell: Shell,
    target_arg: Option<&str>,
    manifest: &Manifest,
) -> Result<Target, String> {
    if let Some(dir) = target_arg {
        let dir = env::expand_tilde(Path::new(dir));
        let path = absolutize(&dir)?.join(shell.file_name());
        return Ok(Target {
            path,
            reason: TargetReason::ExplicitTarget,
        });
    }
    if let Some(entry) = manifest.entry(shell) {
        return Ok(Target {
            path: PathBuf::from(&entry.path),
            reason: TargetReason::PreviousInstall,
        });
    }
    match shell {
        Shell::Bash => Ok(Target {
            path: bash_default_target(),
            reason: TargetReason::BashDefault,
        }),
        Shell::Zsh => {
            if let Some(path) = fpath_target(shell) {
                return Ok(Target {
                    path,
                    reason: TargetReason::Fpath,
                });
            }
            if let Some(path) = oh_my_zsh_target(shell) {
                return Ok(Target {
                    path,
                    reason: TargetReason::OhMyZsh,
                });
            }
            Ok(Target {
                path: env::home_dir().join(".zfunc").join(shell.file_name()),
                reason: TargetReason::HomeDefault,
            })
        }
    }
}

/// The bash adapter location:
/// `${BASH_COMPLETION_USER_DIR:-${XDG_DATA_HOME:-~/.local/share}/bash-completion}/completions/bob`.
fn bash_default_target() -> PathBuf {
    if let Some(dir) = std::env::var_os("BASH_COMPLETION_USER_DIR")
        .filter(|value| !value.is_empty())
    {
        return env::expand_tilde(Path::new(&dir))
            .join("completions")
            .join(Shell::Bash.file_name());
    }
    let data_home = std::env::var_os("XDG_DATA_HOME")
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
        .unwrap_or_else(|| env::home_dir().join(".local/share"));
    data_home
        .join("bash-completion")
        .join("completions")
        .join(Shell::Bash.file_name())
}

/// The fallback target for `status` when resolution needs no manifest.
fn default_target(shell: Shell) -> PathBuf {
    match shell {
        Shell::Bash => bash_default_target(),
        Shell::Zsh => env::home_dir().join(".zfunc").join(shell.file_name()),
    }
}

fn oh_my_zsh_root() -> Option<PathBuf> {
    if let Some(zsh) = std::env::var_os("ZSH").filter(|value| !value.is_empty())
    {
        return Some(env::expand_tilde(Path::new(&zsh)));
    }
    let default = env::home_dir().join(".oh-my-zsh");
    default.is_dir().then_some(default)
}

fn oh_my_zsh_target(shell: Shell) -> Option<PathBuf> {
    let root = oh_my_zsh_root()?;
    let custom = std::env::var_os("ZSH_CUSTOM")
        .filter(|value| !value.is_empty())
        .map(|value| env::expand_tilde(Path::new(&value)))
        .unwrap_or_else(|| root.join("custom"));
    Some(custom.join("completions").join(shell.file_name()))
}

const MANAGER_COMPONENTS: &[&str] = &[
    ".zinit",
    ".zplug",
    ".antigen",
    ".antibody",
    ".sheldon",
    "zcomet",
    ".zcomet",
    "zim",
    ".zim",
    "zgen",
    ".zgen",
    "oh-my-zsh",
    ".oh-my-zsh",
];

fn fpath_target(shell: Shell) -> Option<PathBuf> {
    let entries = verify::fpath_entries()?;
    let home = env::home_dir();
    let omz = oh_my_zsh_root();
    entries
        .iter()
        .map(|entry| env::expand_tilde(entry))
        .find(|dir| is_fpath_candidate(dir, &home, omz.as_deref()))
        .map(|dir| dir.join(shell.file_name()))
}

fn is_fpath_candidate(dir: &Path, home: &Path, omz: Option<&Path>) -> bool {
    // Exclusions apply below $HOME: a `plugins` or cache component above
    // it (a TMPDIR under ~/.cache, for example) says nothing about the
    // entry itself.
    let Ok(relative) = dir.strip_prefix(home) else {
        return false;
    };
    if let Some(root) = omz
        && (dir == root || dir.starts_with(root.join("")))
    {
        return false;
    }
    if relative
        .components()
        .filter_map(|component| component.as_os_str().to_str())
        .any(|name| {
            name == "plugins"
                || name == "cache"
                || name == ".cache"
                || name == "Caches"
                || MANAGER_COMPONENTS.contains(&name)
        })
    {
        return false;
    }
    let metadata = match std::fs::metadata(dir) {
        Ok(metadata) => metadata,
        Err(_) => return false,
    };
    if !metadata.is_dir() {
        return false;
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::MetadataExt;
        if metadata.uid() != current_uid().unwrap_or(u32::MAX) {
            return false;
        }
        use std::os::unix::fs::PermissionsExt;
        if metadata.permissions().mode() & 0o200 == 0 {
            return false;
        }
    }
    true
}

fn current_uid() -> Option<u32> {
    let output = std::process::Command::new("id").arg("-u").output().ok()?;
    if !output.status.success() {
        return None;
    }
    String::from_utf8_lossy(&output.stdout).trim().parse().ok()
}

// --- ownership ------------------------------------------------------------

enum Disk {
    Absent,
    Present { bytes: Vec<u8>, symlink: bool },
}

fn read_disk(path: &Path) -> Disk {
    let symlink = std::fs::symlink_metadata(path)
        .map(|metadata| metadata.file_type().is_symlink())
        .unwrap_or(false);
    match std::fs::read(path) {
        Ok(bytes) => Disk::Present { bytes, symlink },
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            Disk::Absent
        }
        Err(_) => Disk::Present {
            bytes: Vec::new(),
            symlink,
        },
    }
}

struct Classification {
    state: State,
    owned: bool,
    digest: Option<String>,
}

fn classify(shell: Shell, path: &Path, manifest: &Manifest) -> Classification {
    let wanted = adapter_text(shell);
    let entry = manifest.entry(shell);
    let recorded_here =
        entry.is_some_and(|entry| Path::new(&entry.path) == path);
    let owned = recorded_here;
    match read_disk(path) {
        Disk::Absent => Classification {
            state: if entry.is_some() {
                State::Missing
            } else {
                State::NotInstalled
            },
            owned: entry.is_some(),
            digest: None,
        },
        Disk::Present { bytes, .. } => {
            let digest = manifest::sha256_hex(&bytes);
            let stamped = has_stamp(shell, &bytes);
            let state = if !stamped {
                State::Foreign
            } else if recorded_here {
                let entry = entry.expect("recorded entry exists");
                if digest == entry.sha256 {
                    if bytes == wanted.as_bytes() {
                        State::Current
                    } else {
                        State::Outdated
                    }
                } else {
                    State::Edited
                }
            } else if bytes == wanted.as_bytes() {
                State::ExternallyManaged
            } else {
                State::Outdated
            };
            Classification {
                state,
                owned,
                digest: Some(digest),
            }
        }
    }
}

fn is_symlink(path: &Path) -> bool {
    std::fs::symlink_metadata(path)
        .map(|metadata| metadata.file_type().is_symlink())
        .unwrap_or(false)
}

// --- shell selection ------------------------------------------------------

fn select_for_install(
    explicit: Vec<Shell>,
    manifest: &Manifest,
) -> Result<Vec<Shell>, String> {
    if !explicit.is_empty() {
        return Ok(explicit);
    }
    let mut shells = Vec::new();
    if let Some(shell) = std::env::var_os("SHELL")
        .and_then(|value| {
            PathBuf::from(value).file_name().map(|name| name.to_owned())
        })
        .and_then(|name| name.to_str().map(str::to_string))
        .and_then(|name| Shell::parse(&name))
    {
        shells.push(shell);
    }
    for owned in manifest.owned_shells() {
        if !shells.contains(&owned) {
            shells.push(owned);
        }
    }
    if shells.is_empty() {
        return Err(
            "pass a shell: `bob completion install bash` or `bob completion install zsh`"
                .to_string(),
        );
    }
    Ok(shells)
}

// --- install ----------------------------------------------------------------

fn run_install(matches: &clap::ArgMatches) -> i32 {
    let manifest = Manifest::load();
    let explicit = selected_or_all(matches, StatusDefault::Owned(&manifest));
    let shells = match select_for_install(explicit, &manifest) {
        Ok(shells) => shells,
        Err(message) => {
            eprintln!("bob completion install: {message}");
            return 1;
        }
    };
    let target_arg = matches.get_one::<String>("target").map(String::as_str);
    if target_arg.is_some() && shells.len() > 1 {
        eprintln!(
            "bob completion install: --target DIR takes a single shell, got {}",
            shells.len()
        );
        return 2;
    }
    let dry_run = matches.get_flag("dry-run");
    let force = matches.get_flag("force");
    let verify_live = !matches.get_flag("no-verify");
    let quiet = matches.get_flag("quiet");

    let mut manifest = manifest;
    let mut rows = Vec::new();
    let mut failed = false;
    let mut changed = false;
    for shell in shells {
        let target = match resolve_target(shell, target_arg, &manifest) {
            Ok(target) => target,
            Err(message) => {
                rows.push(fail_row(
                    shell,
                    None,
                    &format!("cannot resolve target: {message}"),
                    None,
                ));
                failed = true;
                continue;
            }
        };
        let (row, wrote) = install_one(
            shell,
            &target,
            &mut manifest,
            InstallOptions {
                dry_run,
                force,
                verify_live,
            },
        );
        failed |= row.failed;
        changed |= wrote;
        rows.push(row);
    }
    if !dry_run
        && manifest_changed(&rows)
        && let Err(message) = manifest.save()
    {
        eprintln!("bob completion install: warning: {message}");
    }

    let mut report = Report {
        dry_run,
        rows,
        warnings: Vec::new(),
        closers: Vec::new(),
    };
    if let Some(warning) = verify::path_shadow_warning() {
        report.warnings.push(warning);
    }
    if changed {
        let only_bash = report.rows.iter().all(|row| row.shell == Shell::Bash);
        let only_zsh = report.rows.iter().all(|row| row.shell == Shell::Zsh);
        if only_bash {
            report.closers.push(
                "Open a new shell (or run `exec bash`) to start using it."
                    .to_string(),
            );
        } else if only_zsh {
            report.closers.push(
                "Open a new shell (or run `exec zsh`) to start using it."
                    .to_string(),
            );
        } else {
            report
                .closers
                .push("Open a new shell to start using it.".to_string());
        }
    } else if !failed {
        report.closers.push(format!(
            "Completion is live: every <TAB> asks {}, so new commands work now.",
            tilde_current_exe()
        ));
    }
    emit(&report, false, quiet, failed)
}

struct InstallOptions {
    dry_run: bool,
    force: bool,
    verify_live: bool,
}

fn manifest_changed(rows: &[ShellRow]) -> bool {
    rows.iter().any(|row| row.entry["manifest_write"] == true)
}

#[allow(clippy::too_many_lines)]
fn install_one(
    shell: Shell,
    target: &Target,
    manifest: &mut Manifest,
    options: InstallOptions,
) -> (ShellRow, bool) {
    let wanted = adapter_text(shell);
    let path = &target.path;
    let classification = classify(shell, path, manifest);
    let symlink =
        !matches!(classification.state, State::NotInstalled | State::Missing)
            && is_symlink(path);
    let row_path = report::tilde(&target.path);

    if options.dry_run {
        return dry_run_row(shell, target, &classification, symlink, wanted);
    }

    // A symlink is never bob's own write, even when its bytes match.
    if symlink && !options.force {
        let remedy = format!("bob completion install {} -f", shell.name());
        return (
            ShellRow {
                shell,
                level: Level::Fail,
                summary: "symlink · refused without --force".to_string(),
                path: Some(row_path.clone()),
                notes: vec![format!("→ {remedy}")],
                entry: report::json_entry(
                    shell,
                    State::Foreign,
                    Some(path),
                    classification.owned,
                    "not checked",
                    None,
                    Some(target.reason),
                    Some(remedy),
                ),
                failed: true,
            },
            false,
        );
    }

    // Content that already matches still needs a write when the path is
    // a symlink: only a fresh regular file proves bob wrote it.
    let replace_link = symlink;
    if !replace_link
        && (matches!(classification.state, State::Current)
            || matches!(classification.state, State::ExternallyManaged))
    {
        let registration = verify_and_record(
            shell,
            path,
            classification.digest.as_deref().unwrap_or_default(),
            manifest,
            options.verify_live,
            false,
        );
        return unchanged_row(
            shell,
            target,
            &classification,
            registration,
            manifest,
        );
    }

    if (symlink
        || matches!(classification.state, State::Edited | State::Foreign))
        && !options.force
    {
        let remedy = format!("bob completion install {} -f", shell.name());
        return (
            ShellRow {
                shell,
                level: Level::Fail,
                summary: format!(
                    "{} · refused without --force",
                    classification.state.text()
                ),
                path: Some(row_path),
                notes: vec![format!("→ {remedy}")],
                entry: report::json_entry(
                    shell,
                    classification.state,
                    Some(path),
                    classification.owned,
                    "not checked",
                    None,
                    Some(target.reason),
                    Some(remedy),
                ),
                failed: true,
            },
            false,
        );
    }

    let action = if replace_link {
        "updated"
    } else {
        match classification.state {
            State::NotInstalled | State::Missing => "installed",
            State::Outdated | State::Edited | State::Foreign => "updated",
            State::Current | State::ExternallyManaged => "unchanged",
        }
    };
    if let Err(message) = manifest::atomic_write(path, wanted.as_bytes()) {
        return (
            fail_row(shell, Some(path), &message, Some(target.reason)),
            false,
        );
    }
    remove_zwc(shell, path);
    let digest = manifest::adapter_sha256(shell);
    let registration = if options.verify_live {
        verify::probe_registration(shell, path)
    } else {
        Registration::Unverified("skipped (--no-verify)".to_string())
    };
    let (registration_text, checked) =
        live_or_recorded_text(shell, &registration);
    let verification = VerificationRecord {
        registration: registration_text.clone(),
        digest: digest.clone(),
        path: path.display().to_string(),
        checked: checked.to_string(),
    };
    manifest.set(
        shell,
        super::manifest::ShellEntry {
            path: path.display().to_string(),
            protocol: PROTOCOL,
            sha256: digest,
            bob_version: env!("CARGO_PKG_VERSION").to_string(),
            installed_at: now_rfc3339(),
            target_reason: target.reason.text().to_string(),
            verification: Some(verification),
        },
    );
    let mut entry = report::json_entry(
        shell,
        State::Current,
        Some(path),
        true,
        &registration_text,
        Some(checked),
        Some(target.reason),
        None,
    );
    entry["manifest_write"] = serde_json::Value::Bool(true);
    let mut notes = registration_notes(shell, path, &registration);
    notes.push(format!("({})", target.reason.text()));
    (
        ShellRow {
            shell,
            level: Level::Ok,
            summary: format!(
                "{action} · protocol {PROTOCOL} · {registration_text}"
            ),
            path: Some(row_path),
            notes,
            entry,
            failed: false,
        },
        true,
    )
}

fn dry_run_row(
    shell: Shell,
    target: &Target,
    classification: &Classification,
    symlink: bool,
    wanted: &str,
) -> (ShellRow, bool) {
    let path = &target.path;
    let row_path = report::tilde(&target.path);
    let needs_write = match read_disk(path) {
        Disk::Present { bytes, .. } => bytes != wanted.as_bytes(),
        Disk::Absent => true,
    };
    let refused = symlink
        || (matches!(classification.state, State::Edited | State::Foreign)
            && needs_write);
    let summary = if !needs_write {
        format!("{} · protocol {PROTOCOL}", classification.state.text())
    } else if refused {
        format!("{} · refused without --force", classification.state.text())
    } else {
        format!("would install · protocol {PROTOCOL}")
    };
    let mut notes = vec![format!("({})", target.reason.text())];
    if refused {
        notes.push(format!("→ bob completion install {} -f", shell.name()));
    }
    let entry = report::json_entry(
        shell,
        classification.state,
        Some(path),
        classification.owned,
        "not checked",
        None,
        Some(target.reason),
        refused.then(|| format!("bob completion install {} -f", shell.name())),
    );
    (
        ShellRow {
            shell,
            level: if refused { Level::Warn } else { Level::Plan },
            summary,
            path: Some(row_path),
            notes,
            entry,
            failed: false,
        },
        false,
    )
}

fn unchanged_row(
    shell: Shell,
    target: &Target,
    classification: &Classification,
    registration: LiveRegistration,
    manifest: &Manifest,
) -> (ShellRow, bool) {
    let row_path = report::tilde(&target.path);
    let mut entry = report::json_entry(
        shell,
        classification.state,
        Some(&target.path),
        classification.owned,
        &registration.text,
        registration.checked,
        Some(target.reason),
        None,
    );
    if registration.recorded {
        entry["manifest_write"] = serde_json::Value::Bool(true);
    }
    let _ = manifest;
    let mut notes = registration.notes;
    notes.push(format!("({})", target.reason.text()));
    (
        ShellRow {
            shell,
            level: Level::Ok,
            summary: format!(
                "unchanged · protocol {PROTOCOL} · {}",
                registration.text
            ),
            path: Some(row_path),
            notes,
            entry,
            failed: false,
        },
        false,
    )
}

struct LiveRegistration {
    text: String,
    checked: Option<&'static str>,
    recorded: bool,
    notes: Vec<String>,
}

/// Probe live, or fall back to the recorded result (unchanged path only).
/// Returns the display text plus whether the manifest was updated.
fn verify_and_record(
    shell: Shell,
    path: &Path,
    digest: &str,
    manifest: &mut Manifest,
    verify_live: bool,
    _wrote: bool,
) -> LiveRegistration {
    if !verify_live {
        return LiveRegistration {
            text: recorded_text(shell, path, digest, manifest)
                .unwrap_or_else(|| "registration not checked".to_string()),
            checked: None,
            recorded: false,
            notes: Vec::new(),
        };
    }
    let registration = verify::probe_registration(shell, path);
    let (text, checked) = live_or_recorded_text(shell, &registration);
    let notes = registration_notes(shell, path, &registration);
    manifest.set_verification(
        shell,
        VerificationRecord {
            registration: text.clone(),
            digest: digest.to_string(),
            path: path.display().to_string(),
            checked: checked.to_string(),
        },
    );
    LiveRegistration {
        text,
        checked: Some(checked),
        recorded: true,
        notes,
    }
}

fn recorded_text(
    shell: Shell,
    path: &Path,
    digest: &str,
    manifest: &Manifest,
) -> Option<String> {
    let entry = manifest.entry(shell)?;
    let verification = entry.verification.as_ref()?;
    if verification.path == path.display().to_string()
        && verification.digest == digest
    {
        Some(verification.registration.clone())
    } else {
        None
    }
}

fn live_or_recorded_text(
    shell: Shell,
    registration: &Registration,
) -> (String, &'static str) {
    match registration {
        Registration::Registered => {
            (format!("registered as {}", shell.function_name()), "now")
        }
        other => (other.text(shell), "now"),
    }
}

fn registration_notes(
    shell: Shell,
    path: &Path,
    registration: &Registration,
) -> Vec<String> {
    match registration {
        Registration::Registered => Vec::new(),
        Registration::ShadowedBy(file) => vec![format!(
            "shadowed by {} → remove it or reinstall",
            report::tilde(Path::new(file))
        )],
        Registration::BoundTo(function) => {
            vec![format!(
                "bob is bound to {function}; unbind it, then reload"
            )]
        }
        Registration::NotRegistered { on_fpath } => match shell {
            Shell::Bash => vec![
                "not loaded. Add this line to ~/.bashrc:".to_string(),
                format!("source {}", report::tilde(path)),
            ],
            Shell::Zsh => {
                if *on_fpath {
                    vec![
                        "on your fpath but not loaded. Your compinit dump is stale:"
                            .to_string(),
                        "rm -f \"${ZDOTDIR:-$HOME}\"/.zcompdump* && exec zsh"
                            .to_string(),
                    ]
                } else if let Some(dir) = path.parent() {
                    vec![
                        "not on your fpath. Add this line to ~/.zshrc before compinit:"
                            .to_string(),
                        report::fpath_line(dir),
                    ]
                } else {
                    vec!["not registered".to_string()]
                }
            }
        },
        Registration::Unverified(reason) => {
            vec![format!("verification {reason}")]
        }
    }
}

fn remove_zwc(shell: Shell, path: &Path) {
    if shell != Shell::Zsh {
        return;
    }
    let zwc = path.with_extension("zwc");
    if zwc != path {
        let _ = std::fs::remove_file(zwc);
    }
    if let Some(parent) = path.parent() {
        let _ = std::fs::remove_file(parent.join("_bob.zwc"));
    }
}

fn now_rfc3339() -> String {
    chrono::Local::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, false)
}

fn tilde_current_exe() -> String {
    std::env::current_exe()
        .map(|path| report::tilde(&path))
        .unwrap_or_else(|_| "bob".to_string())
}

fn fail_row(
    shell: Shell,
    path: Option<&Path>,
    message: &str,
    reason: Option<TargetReason>,
) -> ShellRow {
    ShellRow {
        shell,
        level: Level::Fail,
        summary: message.to_string(),
        path: path.map(report::tilde),
        notes: Vec::new(),
        entry: report::json_entry(
            shell,
            State::Missing,
            path,
            false,
            "not checked",
            None,
            reason,
            Some(message.to_string()),
        ),
        failed: true,
    }
}

// --- status -----------------------------------------------------------------

fn run_status(json: bool, live: bool, shells: Vec<Shell>) -> i32 {
    let manifest = Manifest::load();
    let mut rows = Vec::new();
    let mut failed = false;
    for shell in shells {
        let target = resolve_target(shell, None, &manifest).unwrap_or(Target {
            path: default_target(shell),
            reason: match shell {
                Shell::Bash => TargetReason::BashDefault,
                Shell::Zsh => TargetReason::HomeDefault,
            },
        });
        rows.push(status_one(shell, &target, &manifest, live, &mut failed));
    }
    let mut report = Report {
        dry_run: false,
        rows,
        warnings: Vec::new(),
        closers: Vec::new(),
    };
    if let Some(warning) = verify::path_shadow_warning() {
        report.warnings.push(warning);
    }
    emit(&report, json, false, failed)
}

#[allow(clippy::too_many_lines)]
fn status_one(
    shell: Shell,
    target: &Target,
    manifest: &Manifest,
    live: bool,
    failed: &mut bool,
) -> ShellRow {
    let classification = classify(shell, &target.path, manifest);
    let row_path = report::tilde(&target.path);
    let state = classification.state;
    let remedy = status_remedy(shell, state);

    if matches!(state, State::NotInstalled | State::Missing) {
        if live {
            let registration = verify::probe_registration(shell, &target.path);
            let (text, checked) = live_or_recorded_text(shell, &registration);
            *failed |= !registration.healthy();
            let notes = registration_notes(shell, &target.path, &registration);
            return ShellRow {
                shell,
                level: Level::Fail,
                summary: format!("{} · {text}", state.text()),
                path: Some(row_path),
                notes,
                entry: report::json_entry(
                    shell,
                    state,
                    Some(&target.path),
                    classification.owned,
                    &text,
                    Some(checked),
                    Some(target.reason),
                    remedy,
                ),
                failed: !registration.healthy(),
            };
        }
        return ShellRow {
            shell,
            level: Level::Info,
            summary: state.text().to_string(),
            path: Some(row_path),
            notes: remedy
                .clone()
                .map(|remedy| format!("→ {remedy}"))
                .into_iter()
                .collect(),
            entry: report::json_entry(
                shell,
                state,
                Some(&target.path),
                classification.owned,
                "not checked",
                None,
                Some(target.reason),
                remedy,
            ),
            failed: false,
        };
    }

    if live {
        let registration = verify::probe_registration(shell, &target.path);
        let (text, checked) = live_or_recorded_text(shell, &registration);
        let healthy = registration.healthy();
        *failed |= !healthy;
        let mut notes = registration_notes(shell, &target.path, &registration);
        if state != State::Current
            && state != State::ExternallyManaged
            && let Some(remedy) = remedy.clone()
        {
            notes.push(format!("→ {remedy}"));
        }
        return ShellRow {
            shell,
            level: if healthy {
                if state == State::Current || state == State::ExternallyManaged
                {
                    Level::Ok
                } else {
                    Level::Warn
                }
            } else {
                Level::Fail
            },
            summary: format!("{} · protocol {PROTOCOL} · {text}", state.text()),
            path: Some(row_path),
            notes,
            entry: report::json_entry(
                shell,
                state,
                Some(&target.path),
                classification.owned,
                &text,
                Some(checked),
                Some(target.reason),
                remedy,
            ),
            failed: !healthy,
        };
    }

    let digest = classification.digest.as_deref().unwrap_or_default();
    let recorded = recorded_text(shell, &target.path, digest, manifest);
    let text = recorded.unwrap_or_else(|| {
        "registration not checked → bob completion status -v".to_string()
    });
    let level = match state {
        State::Current | State::ExternallyManaged => Level::Ok,
        State::Outdated | State::Edited | State::Foreign => Level::Warn,
        State::NotInstalled | State::Missing => Level::Info,
    };
    let mut notes = Vec::new();
    if let Some(remedy) = remedy.clone()
        && !matches!(state, State::Current | State::ExternallyManaged)
    {
        notes.push(format!("→ {remedy}"));
    }
    ShellRow {
        shell,
        level,
        summary: format!("{} · protocol {PROTOCOL} · {text}", state.text()),
        path: Some(row_path),
        notes,
        entry: report::json_entry(
            shell,
            state,
            Some(&target.path),
            classification.owned,
            &text,
            recorded_checked(manifest, shell, &target.path, digest),
            Some(target.reason),
            remedy,
        ),
        failed: false,
    }
}

fn recorded_checked(
    manifest: &Manifest,
    shell: Shell,
    path: &Path,
    digest: &str,
) -> Option<&'static str> {
    let entry = manifest.entry(shell)?;
    let verification = entry.verification.as_ref()?;
    (verification.path == path.display().to_string()
        && verification.digest == digest)
        .then_some("install")
}

fn status_remedy(shell: Shell, state: State) -> Option<String> {
    match state {
        State::NotInstalled | State::Missing | State::Outdated => {
            Some(format!("bob completion install {}", shell.name()))
        }
        State::Edited | State::Foreign => {
            Some(format!("bob completion install {} -f", shell.name()))
        }
        State::Current | State::ExternallyManaged => None,
    }
}

// --- uninstall ---------------------------------------------------------------

fn run_uninstall(matches: &clap::ArgMatches) -> i32 {
    let manifest = Manifest::load();
    let explicit = selected_or_all(matches, StatusDefault::Owned(&manifest));
    let dry_run = matches.get_flag("dry-run");

    let mut manifest = manifest;
    let mut rows = Vec::new();
    let mut failed = false;
    let mut changed = false;
    for shell in explicit {
        let Some(entry) = manifest.entry(shell).cloned() else {
            rows.push(ShellRow {
                shell,
                level: Level::Info,
                summary: "not installed".to_string(),
                path: None,
                notes: Vec::new(),
                entry: report::json_entry(
                    shell,
                    State::NotInstalled,
                    None,
                    false,
                    "not checked",
                    None,
                    None,
                    None,
                ),
                failed: false,
            });
            continue;
        };
        let path = PathBuf::from(&entry.path);
        let (row, removed) =
            uninstall_one(shell, &path, &entry.sha256, dry_run);
        failed |= row.failed;
        changed |= removed && !dry_run;
        if removed && !dry_run {
            manifest.remove(shell);
        }
        rows.push(row);
    }
    if changed && let Err(message) = manifest.save() {
        eprintln!("bob completion uninstall: warning: {message}");
    }
    let mut report = Report {
        dry_run,
        rows,
        warnings: Vec::new(),
        closers: Vec::new(),
    };
    if changed {
        report.closers.push(
            "Open a new shell to drop the loaded completion.".to_string(),
        );
    } else if !failed && report.rows.is_empty() {
        report
            .closers
            .push("No bob-owned adapters installed.".to_string());
    }
    emit(&report, false, false, failed)
}

fn uninstall_one(
    shell: Shell,
    path: &Path,
    recorded_sha: &str,
    dry_run: bool,
) -> (ShellRow, bool) {
    let row_path = report::tilde(path);
    let rm_command = format!("rm {:?}", path.display().to_string());
    match read_disk(path) {
        Disk::Absent => (
            ShellRow {
                shell,
                level: Level::Ok,
                summary: "already gone · manifest entry dropped".to_string(),
                path: Some(row_path),
                notes: Vec::new(),
                entry: report::json_entry(
                    shell,
                    State::Missing,
                    Some(path),
                    true,
                    "not checked",
                    None,
                    None,
                    None,
                ),
                failed: false,
            },
            true,
        ),
        Disk::Present { bytes, symlink } => {
            let digest = manifest::sha256_hex(&bytes);
            let proven =
                has_stamp(shell, &bytes) && digest == recorded_sha && !symlink;
            if !proven {
                return (
                    ShellRow {
                        shell,
                        level: Level::Fail,
                        summary: "edited · not removed".to_string(),
                        path: Some(row_path),
                        notes: vec![format!("run this instead: {rm_command}")],
                        entry: report::json_entry(
                            shell,
                            State::Edited,
                            Some(path),
                            true,
                            "not checked",
                            None,
                            None,
                            Some(rm_command),
                        ),
                        failed: true,
                    },
                    false,
                );
            }
            if dry_run {
                return (
                    ShellRow {
                        shell,
                        level: Level::Plan,
                        summary: "would remove".to_string(),
                        path: Some(row_path),
                        notes: Vec::new(),
                        entry: report::json_entry(
                            shell,
                            State::Current,
                            Some(path),
                            true,
                            "not checked",
                            None,
                            None,
                            None,
                        ),
                        failed: false,
                    },
                    false,
                );
            }
            match std::fs::remove_file(path) {
                Ok(()) => {
                    remove_zwc(shell, path);
                    (
                        ShellRow {
                            shell,
                            level: Level::Ok,
                            summary: "removed".to_string(),
                            path: Some(row_path),
                            notes: Vec::new(),
                            entry: report::json_entry(
                                shell,
                                State::NotInstalled,
                                Some(path),
                                false,
                                "not checked",
                                None,
                                None,
                                None,
                            ),
                            failed: false,
                        },
                        true,
                    )
                }
                Err(error) => (
                    fail_row(
                        shell,
                        Some(path),
                        &format!("cannot remove {}: {error}", path.display()),
                        None,
                    ),
                    false,
                ),
            }
        }
    }
}

// --- print -------------------------------------------------------------------

fn run_print(shell: Shell, output: Option<&String>) -> i32 {
    let text = adapter_text(shell);
    match output {
        None => {
            print!("{text}");
            0
        }
        Some(file) => {
            let path = env::expand_tilde(Path::new(file));
            let path = match absolutize(&path) {
                Ok(path) => path,
                Err(message) => {
                    eprintln!("bob completion {}: {message}", shell.name());
                    return 1;
                }
            };
            match manifest::atomic_write(&path, text.as_bytes()) {
                Ok(()) => 0,
                Err(message) => {
                    eprintln!("bob completion {}: {message}", shell.name());
                    1
                }
            }
        }
    }
}

// --- emit --------------------------------------------------------------------

fn emit(report: &Report, json: bool, quiet: bool, failed: bool) -> i32 {
    if json {
        println!("{}", report.render_json());
    } else {
        print!("{}", report.render_human(Styler::detect(), quiet));
    }
    if failed {
        1
    } else {
        0
    }
}
